{
  "controlTypeValues": {
    "TcHmi.Controls.ParisonFramework.ParisonFrameworkControl": {
      "attributes": {},
      "themedResources": {
        "ParisonLayer2Color": {
          "color": "rgba(51, 31, 0, 1)"
        },
        "ParisonBasicLayerColor": {
          "color": "rgba(170, 59, 0, 1)"
        },
        "ParisonLayer3Color": {
          "color": "rgba(251, 102, 102, 1)"
        },
        "ParisonLayer4Color": {
          "color": "rgba(44, 1, 1, 1)"
        },
        "ParisonLayer5Color": {
          "color": "rgba(255, 4, 4, 1)"
        },
        "ParisonVariableLayerBaseColor": {
          "color": "rgba(0, 0, 0, 1)"
        },
        "ParisonSpoolColor": {
          "color": "rgba(255, 255, 20, 1)"
        },
        "Parison3DBackgroundColor": {
          "color": "rgba(255, 255, 255, 1)"
        }
      }
    }
  },
  "controlClassValues": {
    "inputbox_toggle_switch": {
      "attributes": {},
      "themedResources": {}
    },
    "SliderTab": {
      "attributes": {},
      "themedResources": {}
    },
    "Tiles": {
      "attributes": {},
      "themedResources": {}
    },
    "TilesHeadline": {
      "attributes": {},
      "themedResources": {}
    }
  },
  "$schema": "./../../../Packages/Beckhoff.TwinCAT.HMI.Framework.14.1.15/runtimes/native1.12-tchmi/Schema/ThemeDescription.Schema.json"
}