<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{745e0018-9c54-4e6b-8afc-5f6b8fa0e4a0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
						
	// CurveEditor Varaibles
	fbWTC1: FB_CamWTC;
	fbWTC2: FB_CamWTC;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbWTC1();
fbWTC2();




]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>